version: "3.8"
services:
  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: imager
      POSTGRES_PASSWORD: imager
      POSTGRES_DB: imager
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data:
